## 필요한 데이터만 추출하기

In [3]:
import pandas as pd
import os

def load_hotel_reserve():
  customer_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/customer.csv')
  hotel_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/hotel.csv')
  reserve_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/reserve.csv')
  return customer_tb, hotel_tb, reserve_tb


def load_holiday_mst():
  holiday_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/holiday_mst.csv',
                           index_col=False)
  return holiday_tb


def load_production():
  production_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/production.csv')
  return production_tb


def load_production_missing_num():
  production_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/production_missing_num.csv')
  return production_tb


def load_production_missing_category():
  production_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/production_missing_category.csv')
  return production_tb


def load_monthly_index():
  monthly_index_tb = \
    pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/monthly_index.csv')
  return monthly_index_tb


def load_meros_txt():
  with open('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/txt/meros.txt', 'r') as f:
    meros = f.read()
    f.close()
  return meros

In [4]:
customer_tb, hotel_tb, reserve_tb = load_hotel_reserve()

print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [ ]:
reserve_tb[['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime',
            'checkin_date', 'checkin_time', 'checkout_date']]
# 지정된 데이터 열 추출하는 방법1
# reserve_tb의 배열에 추출할 열 이름을 문자열으로 직접 지정
print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [ ]:
reserve_tb.loc[:, ['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime',
                   'checkin_date', 'checkin_time', 'checkout_date']]
# 방법2. 숫자 위치(인덱스)로 지정
# .loc란 행과 열을 이름 기준으로 선택하는 방법. df.loc[행 조건, 열 조건], : 이 뜻은 행은 전부 가져오라는 뜻
# .loc[조건, ['a','b']] 행 조건 + 열 선택을 동시에 할 수 있음
print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [ ]:
reserve_tb.drop(['people_num', 'total_price'], axis=1, inplace=True)
# 방법3. people,total 두 컬럼을 삭제. axis=1은 열 방향으로 작업(=여기선 삭제).inplace=True는 원본 자체를 바꿔버림
# axis=0은 행(가로) 방향이라는 뜻이고 drop에서는 행을 삭제한다는 뜻
# 이 코드는 reserve_tb에서 인원수,총금액 컬럼을 삭제한 

print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date
0        10:00:00    2016-03-29
1        11:30:00    2016-07-21
2        09:00:00    2016-10-22
3        11:00:00    2017-03-30
4        10:30:00    2017-09-23
...           ...           ...
4025     09:30:00    2017-07-11
4026     10:30:00    2017-10-10
4027     11:30:00    2018-04-04
4028     09:30:00    2016-05-13
4029     09:00:00    2016-07-09

[4030 rows x 7 columns]

## 조건을 부여되어 있는 데이터 행 추출

In [ ]:
reserve_tb[(reserve_tb['checkout_date'] >= '2016-10-13') &
           (reserve_tb['checkout_date'] <= '2016-10-14')]
# 방법1 : DataFrame 배열에 지정한 조건의 결과값인 True/False를 가지는 행의 배열을 지정하여 추출
# 각 행마다 조건이 맞으면 True, 아니면 False를 반환, 두 조건이 모두 True인 행만 추출

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [ ]:
reserve_tb.loc[(reserve_tb['checkout_date'] >= '2016-10-13') &
               (reserve_tb['checkout_date'] <= '2016-10-14'), :]    
#  loc 함수의 2차원 배열의 1차원 항목에 지정한 조건의 결과값인 True/False를 지정하여 추출
# loc함수로 행 조건을 걸었고, 열은 전부 다 추출하라는 코드

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [ ]:
reserve_tb.query('"2016-10-13" <= checkout_date <= "2016-10-14"')
# 방법3 : Query함수와 조건식을 이용하여 행을 추출
# .query()는 조건을 문자열로 써서 행을 필터링하는 방법. 컬럼명만 바로 쓸수 있음

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [ ]:
reserve_tb.sample(frac=0.5)
#reserve테이블에서 50% 샘플링하는 코

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
1926,r1927,h_180,c_475,2018-01-28 09:27:52,2018-02-18,12:30:00,2018-02-20
3357,r3358,h_230,c_839,2016-08-14 00:14:00,2016-09-10,09:00:00,2016-09-12
3578,r3579,h_109,c_888,2016-11-23 15:07:58,2016-11-24,11:00:00,2016-11-25
2357,r2358,h_158,c_593,2016-06-16 16:38:21,2016-06-23,10:00:00,2016-06-26
3029,r3030,h_75,c_765,2017-03-14 11:27:35,2017-03-25,10:00:00,2017-03-26
...,...,...,...,...,...,...,...
1006,r1007,h_182,c_247,2016-04-27 01:22:36,2016-05-10,11:30:00,2016-05-12
162,r163,h_70,c_36,2016-06-29 10:35:22,2016-07-19,11:00:00,2016-07-22
1355,r1356,h_156,c_332,2017-01-16 19:17:27,2017-02-12,09:30:00,2017-02-14
800,r801,h_101,c_195,2016-04-02 09:47:38,2016-04-30,09:30:00,2016-05-01
3556,r3557,h_152,c_882,2018-10-16 10:20:50,2018-10-23,09:30:00,2018-10-26

In [ ]:
target= pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)  
#unique함수로 customer_id 컬럼의 중복 제거된 고유값 배열을 반환(예약 사람 목록만 남김)
# pd.Series는 그 배열을 pandas series로 변환.
# .sample(frac=0.5) 고유 customer_id 중 무작위로 50% 추출

print(target)   # customer_id가 100명이면 target에는 무작위로 선택된 50명의 id가 담김

reserve_tb[reserve_tb['customer_id'].isin(target)]
# .isin(target)는 customer_id가 target에 포함된 행만 true. 결과는 target에 선택된 50% 고객의 모든 예약기록을 반환

834    c_939
274    c_315
625    c_710
647    c_736
669    c_759
       ...
852    c_962
638    c_724
176    c_205
716    c_812
707    c_802
Length: 444, dtype: object

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
16,r17,h_115,c_3,2016-05-10 12:20:32,2016-05-17,10:00:00,2016-05-19
17,r18,h_132,c_3,2016-10-22 02:18:48,2016-11-12,12:00:00,2016-11-13
18,r19,h_23,c_3,2017-01-11 22:54:09,2017-02-08,10:00:00,2017-02-10
19,r20,h_292,c_3,2017-02-23 07:10:30,2017-03-03,11:00:00,2017-03-04
20,r21,h_153,c_3,2017-04-06 18:12:10,2017-04-16,09:00:00,2017-04-19
...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09

In [10]:
result = reserve_tb \
        .groupby('hotel_id') \
        .agg({'reserve_id' : 'count', 'customer_id': 'nunique' })

result

# nunique()는 중복제거된 값의 개수만 반환 / unique()는 중복 제거된 값 자체를 반환
# 호텔별로 묶어서, 전체 예약 개수와 서로 다른 고객(중복제거)를 계산하는 코드
# 호텔별로 얼마나 예약이 많이 들어왔고 몇명의 서로 다른 고객이 이용했는지를 보는것
# .agg()는 집계의 줄임말로 컬럼마다 서로 다른 집계함수를 동시에 적용할 수 있는 메서드
# 'reserve_id' : 'count'는 예약건수(중복 포함 전체 개수), 'customer_id': 'nunique'는 실제 방문고객수(중복제거)



# 위의 코드 상태까지는 hotel_id가 컬럼이 아니라 인덱스로 있는 상태. 일반 컬럼으로 바꿔줘야함
result.reset_index(inplace=True)                #일반 컬럼으로 바뀜, True니까 원본 자체를 바꿔버림
result.columns = ['hotel_id', 'rsv_cnt', 'cus_cnt']     #컬럼이름을 리스트로 통쨰로 교체하는 방식
        #reserve_id가 rsv_cnt, customer_id가 cus_cnt라는 컬럼명으로 바뀜
result

    hotel_id  rsv_cnt  cus_cnt
0        h_1       10       10
1       h_10        3        3
2      h_100       20       19
3      h_101       17       17
4      h_102       13       13
..       ...      ...      ...
295     h_95       13       13
296     h_96       13       13
297     h_97       16       16
298     h_98       17       16
299     h_99       14       14

[300 rows x 3 columns]

In [ ]:
# 위의 코드 상태까지는 hotel_id가 컬럼이 아니라 인덱스로 있는 상태. 일반 컬럼으로 바꿔줘야함
result.reset_index(inplace=True)                #일반 컬럼으로 바뀜, True니까 원본 자체를 바꿔버림
result.columns = ['hotel_id', 'rsv_cnt', 'cus_cnt']     #컬럼이름을 리스트로 통쨰로 교체하는 방식
        #reserve_id가 rsv_cnt, customer_id가 cus_cnt라는 컬럼명으로 바뀜
result

    hotel_id  rsv_cnt  cus_cnt
0        h_1       10       10
1       h_10        3        3
2      h_100       20       19
3      h_101       17       17
4      h_102       13       13
..       ...      ...      ...
295     h_95       13       13
296     h_96       13       13
297     h_97       16       16
298     h_98       17       16
299     h_99       14       14

[300 rows x 3 columns]

In [16]:
print(reserve_tb.columns)

Index(['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime',
       'checkin_date', 'checkin_time', 'checkout_date'],
      dtype='object')

In [17]:
reserve_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/reserve.csv')

In [13]:
# 호텔 + 인원수별로 총 매출 합계 구하는 코드 / 각 호텔에서 인원수별로 총 얼마를 벌었는지 구하는 코드
# \ 이건 줄바꿈(코드 이어쓰기) 용도
result = reserve_tb \
    .groupby(['hotel_id', 'people_num'])['total_price'] \
    .sum().reset_index()
# 호텔이랑 인원수랑 groupby해서 하나의 그룹이 되었고 그 그룹의 total_price합계를 구하는것

result.rename(columns={'total_price': 'price_sum'}, inplace=True)
print(result)

     hotel_id  people_num  price_sum
0         h_1           1     156600
1         h_1           2     156600
2         h_1           3     391500
3         h_1           4     417600
4        h_10           1      11200
...       ...         ...        ...
1154     h_98           3     793800
1155     h_98           4     453600
1156     h_99           1     179200
1157     h_99           2     448000
1158     h_99           4    1164800

[1159 rows x 3 columns]

In [ ]:
import numpy as np
# 예약데이터에서 호텔별로 묶고, total_price에 5가지 통계 한번에 계산
result=reserve_tb \
       .groupby('hotel_id') \
       .agg({'total_price': ['max', 'min','mean','median',     #한 컬럼에 여러 함수를 리스트로 동시에
                             lambda x : np.percentile(x, q=20)]}) \
       .reset_index()        # x(호텔별 가격 목록 전체)를 받아서 하위 20% 값
result.columns=['hotel_id', 'price_max','price_min','price_mean',
                'price_median','price_20per']

print(result)

    hotel_id  price_max  price_min     price_mean  price_median  price_20per
0        h_1     208800      26100  112230.000000      104400.0      73080.0
1       h_10      67200      11200   42933.333333       50400.0      26880.0
2      h_100      57600       4800   27600.000000       28800.0       9600.0
3      h_101     168000      14000   75764.705882       56000.0      30800.0
4      h_102      72000      12000   32769.230769       24000.0      18000.0
..       ...        ...        ...            ...           ...          ...
295     h_95     518400      43200  275815.384615      259200.0     146880.0
296     h_96      66600       7400   33015.384615       29600.0      17760.0
297     h_97     250800      20900   83600.000000       62700.0      20900.0
298     h_98     226800      18900   96723.529412       75600.0      56700.0
299     h_99     268800      44800  128000.000000       89600.0      67200.0

[300 rows x 6 columns]

var = 분산, 차이의 제곱의 평균

std = 표준편차, 분산의 제곱근

In [ ]:
# 호텔별로 묶고, total_price의 분산,표준편차를 계산하고 NaN을 0으로 채우기
result = reserve_tb.groupby('hotel_id')\
    .agg({'total_price': ['var','std']}).reset_index()
result.columns=['hotel_id','price_var','price_std']

result.fillna(0, inplace=True)  # NaN을 전부 0으로 교체하고 원본으로 바뀜
# NaN ≠ None 이지만 pandas 안에서는 둘 다 "빈값"으로 동일하게 처리됨— NaN은 숫자 연산이 불가능할 때 나오는 float 특수값

result

    hotel_id     price_var      price_std
0        h_1  3.186549e+09   56449.526127
1       h_10  8.258133e+08   28736.968061
2      h_100  3.198316e+08   17883.835689
3      h_101  2.402441e+09   49014.703676
4      h_102  3.576923e+08   18912.755159
..       ...           ...            ...
295     h_95  3.313772e+10  182037.696857
296     h_96  3.159231e+08   17774.225072
297     h_97  5.474685e+09   73991.116584
298     h_98  3.432893e+09   58590.896578
299     h_99  5.745428e+09   75798.599541

[300 rows x 3 columns]

In [ ]:
#최빈값 계산하는 코드 / round(-3)해서 천단위로 반올림,비슷한 가격대 묶기, mode는 가장 자주 등장하는 값 추출
reserve_tb['total_price'].round(-3).mode()

0    10000
1    20000
2    40000
Name: total_price, dtype: int64

In [ ]:
#문자열로 저장된 날짜를 진짜 날짜 타입으로 변환하는 코드
reserve_tb['reserve_datetime']=pd.to_datetime(  #datetime으로 변환을 해야 계산,추출 가능
    reserve_tb['reserve_datetime'],     # 변환할 컬럼
    format='%Y-%m-%d %H:%M:%S'          # 원본 문자열 형식을 지정해줌
)

In [25]:
#고객별로 묶고 예약날짜 순서대로 몇번째 예약인지 번호를 매기는 코드

reserve_tb['log_no']=reserve_tb \
    .groupby('customer_id')['reserve_datetime'] \
    .rank(ascending=True, method='first')   #ascending=True는 오래된 날짜가 1번, 최근 날짜가 큰 번호, 첫 예약이 1번
    # method='first' 날짜가 완전히 같을때 먼저 나온 행이 낮은 번호다 라는 뜻
reserve_tb
#log_no라는 컬럼으로 고객의 몇번째 예약인지 추적 가능
# log_no=1만 필터링 하면 신규고객 첫 예약만 분석할 수 있음
# log_no가 클수록 단골 고객을 파악할 수 있음

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0
...,...,...,...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13,4,540000,1.0
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0

In [ ]:
# 호텔별로 묶은 다음에 각 호텔 그룹의 행 수를 세고, 인덱스에 갇혀있던 hotel_id를 컬럼으로 꺼내고
# 컬럼이름을 hotel_id, resv_cnt로 붙이는 것
rsv_cnt_tb=reserve_tb.groupby('hotel_id').size().reset_index()  #size는 행의 개수를 샌다
rsv_cnt_tb.columns=['hotle_id','rsv_cnt']

rsv_cnt_tb

    hotle_id  rsv_cnt
0        h_1       10
1       h_10        3
2      h_100       20
3      h_101       17
4      h_102       13
..       ...      ...
295     h_95       13
296     h_96       13
297     h_97       16
298     h_98       17
299     h_99       14

[300 rows x 2 columns]

## rank() method — 동률 처리 방식
- `ascending=False` : 큰 값 → 1위 (예약 많은 호텔이 1등)
- `method='min'` : 동률이면 **공동 낮은 번호** → 1,1,3 (스포츠 순위표 방식)
- `method='first'` : 동률이면 **먼저 나온 행이 낮은 번호** → 1,2,3 (무조건 다른 번호)
- `method='average'` : 동률이면 **평균 순위** → 1.5,1.5,3

In [ ]:
# rsv_cnt_tb의 rsv_cnt컬럼을 예약 많은 순으로 순위를 매기고 그걸 새 컬럼으로 추가하는 코드
rsv_cnt_tb['rsv_cnt_rank']=rsv_cnt_tb['rsv_cnt'].rank(ascending=False, method='min')
                                        #ascending=False는 큰값에 낮은 순위번호
rsv_cnt_tb

    hotle_id  rsv_cnt  rsv_cnt_rank
0        h_1       10         235.0
1       h_10        3         300.0
2      h_100       20          12.0
3      h_101       17          43.0
4      h_102       13         139.0
..       ...      ...           ...
295     h_95       13         139.0
296     h_96       13         139.0
297     h_97       16          60.0
298     h_98       17          43.0
299     h_99       14         115.0

[300 rows x 3 columns]

In [ ]:
rsv_cnt_tb.drop('rsv_cnt', axis=1,inplace=True) #rsv_cnt 열 제거하고 그걸 저장

rsv_cnt_tb

    hotle_id  rsv_cnt_rank
0        h_1         235.0
1       h_10         300.0
2      h_100          12.0
3      h_101          43.0
4      h_102         139.0
..       ...           ...
295     h_95         139.0
296     h_96         139.0
297     h_97          60.0
298     h_98          43.0
299     h_99         115.0

[300 rows x 2 columns]

## 여러테이블 합치기

In [ ]:
pd.merge(reserve_tb.query('people_num==1'),         #예약테이블에서 1인 예약 데이터만 필터링
         hotel_tb.query('is_business'),             # 호텔 테이블에서 비즈니스호텔만
         on='hotel_id', how='inner')            # on='hotel_id'는 두 테이블을 이 컬럼 기준으로 합친다는것
# how=inner 는 양쪽 다 있는 것만, 두 조건 모두 만족하는 데이터만 남아야한다는 것

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,base_price,big_area_name,small_area_name,hotel_latitude,hotel_longitude,is_business
0,r7,h_256,c_1,2017-12-29 10:38:36,2018-01-25,10:30:00,2018-01-28,1,103500,7.0,34500,C,C-1,38.237294,140.696131,True
1,r11,h_183,c_2,2016-11-19 12:49:10,2016-12-08,11:00:00,2016-12-11,1,29700,3.0,9900,G,G-4,33.595248,130.633567,True
2,r13,h_223,c_2,2017-10-19 03:03:30,2017-10-21,09:30:00,2017-10-23,1,137000,5.0,68500,C,C-2,38.329097,140.698165,True
3,r18,h_132,c_3,2016-10-22 02:18:48,2016-11-12,12:00:00,2016-11-13,1,20400,2.0,20400,C,C-1,38.231842,140.797268,True
4,r25,h_277,c_4,2016-03-28 07:17:34,2016-04-07,10:30:00,2016-04-10,1,39300,1.0,13100,C,C-1,38.233985,140.795603,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,r3999,h_72,c_993,2016-06-09 04:35:48,2016-07-04,12:00:00,2016-07-07,1,29100,2.0,9700,B,B-2,35.545712,139.596157,True
442,r4001,h_253,c_993,2017-01-20 18:50:35,2017-02-10,11:00:00,2017-02-12,1,10400,4.0,5200,C,C-3,38.430220,140.696571,True
443,r4005,h_150,c_994,2016-03-25 11:51:26,2016-04-02,09:00:00,2016-04-03,1,25200,1.0,25200,B,B-2,35.546229,139.693687,True
444,r4011,h_137,c_995,2017-08-13 19:23:48,2017-09-07,09:30:00,2017-09-09,1,12400,6.0,6200,F,F-1,34.538252,132.469507,True
445,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0,14700,A,A-3,35.912979,139.832314,True

In [ ]:
import gc

small_area_mst = hotel_tb \
    .groupby(['big_area_name', 'small_area_name'], as_index=False) \
    .size().reset_index()
# 호텔 테이블에서 big area + small area로 묶고 인덱스 말고 컬럼으로 만들고, 행 수를 세고,
# 인덱스를 해제해서 컬럼으로 꺼냄
print(small_area_mst)

small_area_mst.columns=['index','big_area_name','small_area_name','hotel_cnt']
# as_index=False + reset_index() 둘 다 써서 컬럼이 하나 더 생겼으니까 이름 부여

small_area_mst['join_area_id']= \
 np.where(small_area_mst['hotel_cnt']-1 >= 20,  # 호텔 수에서 자기 자신 뺴고 20개 이상이면 small,
          small_area_mst['small_area_name'],    # 아니면 big으로 넣어서 join_area_id 컬럼을 생성
          small_area_mst['big_area_name'])

small_area_mst.drop(['hotel_cnt','big_area_name'],axis=1,inplace=True)
# 재료로 쓴 hotel_cnt, big_area_name 컬럼 삭제하고 원본에 저장

base_hotel_mst=pd.merge(hotel_tb, small_area_mst, on='small_area_name') \
                .loc[:, ['hotel_id', 'join_area_id']]
# 호텔 테이블이랑 small_area_mst를 small_area_name 기준으로 합치고, 
# 전체 행에서 hotel_id랑 join_area_id 컬럼만 추출

del small_area_mst      # 중간에 만든 임시 테이블 삭제하고 메모리 정리
gc.collect()

    index big_area_name small_area_name  size
0       0             A             A-1    35
1       1             A             A-3    30
2       2             B             B-1    15
3       3             B             B-2    18
4       4             B             B-3    19
5       5             C             C-1    25
6       6             C             C-2    30
7       7             C             C-3    21
8       8             D             D-1     7
9       9             D             D-2     7
10     10             D             D-3     7
11     11             D             D-4     5
12     12             E             E-1     8
13     13             E             E-2     5
14     14             E             E-3     4
15     15             E             E-4     9
16     16             F             F-1     6
17     17             F             F-2     5
18     18             F             F-3    11
19     19             F             F-4     7
20     20             G             G-1     9
21     21             G             G-2     4
22     22             G             G-3     6
23     23             G             G-4     7

0

## 추천 호텔 테이블 만들기

**목적**: 내가 예약한 호텔 근처의 다른 호텔을 추천해주는 테이블 생성

**"근처"의 기준**
- 소지역 호텔 수 >= 20 → 소지역 기준으로 추천
- 소지역 호텔 수 < 20  → 대지역 기준으로 추천 (호텔이 적으니까 범위를 넓힘)

**흐름**
1. 소지역/대지역 테이블을 join_area_id로 rename 후 concat (위아래로 쌓기)
2. hotel_id → rec_hotel_id로 rename (merge시 컬럼 구분용)
3. base_hotel_mst랑 join_area_id 기준으로 merge
4. 자기 자신 제외 (hotel_id != rec_hotel_id)

**최종 결과**
| hotel_id | rec_hotel_id |
|----------|-------------|
| H001     | H002        | ← H001 근처 호텔 추천
| H001     | H003        |

In [ ]:
# 예약한 호텔 근처에 있는 다른 호텔들을 추천하는 코드
#pd.concat은 위아래로 쌓는거라 컬럼 이름이 같아야함.

# 1단계 - 소지역/대지역 테이블을 위아래로 쌓기
recommend_hotel_mst=pd.concat([
    hotel_tb[['small_area_name', 'hotel_id']] \
    .rename(columns={'small_area_name': 'join_area_id'}, inplace=False), 

    hotel_tb[['big_area_name', 'hotel_id']] \
    .rename(columns={'big_area_name': 'join_area_id'}, inplace=False)
])  #concat은 위아래로 쌓는거라서 컬럼이름이 같아야하므로 둘다 join_area_id로 rename하고 쌓음

# 2단계 - 컬럼명 변경
recommend_hotel_mst.rename(columns={'hotel_id' : 'rec_hotel_id'}, inplace=True)
# 나중에 merge할때 hotel_id가 두 테이블에 다 있으면 헷갈리니까 구분해줌

# 3단계 - merge + 필요한 컬럼만 + 자기 자신 제외
pd.merge(base_hotel_mst, recommend_hotel_mst, on='join_area_id') \
    .loc[:, ['hotel_id', 'rec_hotel_id']] \
    .query('hotel_id != rec_hotel_id')
# join_area_id 기준으로 같은 지역 호텔끼리 연결하고 2개 컬럼만 추출. 자기 자신은 추천해서 제외

     hotel_id rec_hotel_id
1         h_1         h_14
2         h_1         h_22
3         h_1         h_27
4         h_1         h_40
5         h_1         h_45
...       ...          ...
9658    h_300        h_247
9659    h_300        h_256
9660    h_300        h_257
9661    h_300        h_277
9662    h_300        h_295

[9364 rows x 2 columns]

In [29]:
# 고객별로 그룹지어서, 각 그룹을 예약일자 순으로 정렬하는 코드
# .apply()는 그룹을 통쨰로 받아서 가공
result = reserve_tb \
     .groupby('customer_id') \
        .apply(lambda group:        #위의 코드는 고객별 그룹을 생성하고, 각 그룹에 함수를 적용하는거.
            group.sort_values(by='reserve_datetime', axis=0, inplace=False),
            #group는 한고객의 예약 데이터 전체.
            include_groups=False)
#각 그룹에 함수를 적용.
#  group.sort_values(by='reserve_datetime', axis=0, inplace=False)는 reserve_datetime을 기준으로 오름차순 정렬하는 코드
# axis=0은 행 방향으로 정렬, inplace=False는 원본 데이터프레임을 변경하지 않고 정렬된 결과를 반환하는 코드

result

                 reserve_id hotel_id     reserve_datetime checkin_date  \
customer_id
c_1         0            r1     h_75  2016-03-06 13:09:42   2016-03-26
            1            r2    h_219  2016-07-16 23:39:55   2016-07-20
            2            r3    h_179  2016-09-24 10:03:17   2016-10-19
            3            r4    h_214  2017-03-08 03:20:10   2017-03-29
            4            r5     h_16  2017-09-05 19:50:37   2017-09-22
...                     ...      ...                  ...          ...
c_999       4023      r4024    h_244  2016-10-06 18:01:34   2016-10-07
            4024      r4025    h_160  2017-03-11 11:56:05   2017-03-27
            4025      r4026    h_129  2017-06-27 23:00:02   2017-07-10
            4026      r4027     h_97  2017-09-29 05:24:57   2017-10-09
            4027      r4028     h_27  2018-03-14 05:01:45   2018-04-02

                 checkin_time checkout_date  people_num  total_price  log_no
customer_id
c_1         0        10:00:00    2016-03-29           4        97200     1.0
            1        11:30:00    2016-07-21           2        20600     2.0
            2        09:00:00    2016-10-22           2        33600     3.0
            3        11:00:00    2017-03-30           4       194400     4.0
            4        10:30:00    2017-09-23           3        68100     5.0
...                       ...           ...         ...          ...     ...
c_999       4023     11:30:00    2016-10-09           3        59400     2.0
            4024     10:00:00    2017-03-30           1        37200     3.0
            4025     09:30:00    2017-07-11           2        16000     4.0
            4026     10:30:00    2017-10-10           2        41800     5.0
            4027     11:30:00    2018-04-04           2        74800     6.0

[4030 rows x 9 columns]

In [ ]:
# .shift()는 데이터를 아래로 밀어내는 함수. 이 코드는 2칸 아래로 밀기
result['before_price']= \
    pd.Series(result['total_price'].shift(periods=2))
# 2칸 밀렸으니까 위에 2개는 NaN
# shift 없이는 2번전 값을 현재 행에 붙일 방법이 없고, 실무에서 분석할때
# 2번 전 예약보다 이번에 더 비싼 호텔을 예약했고 구매력이 올라가고있다. 이런 변화를 볼 수 있음

result

# 위의 코드에서 apply로 고객별 정렬을 해서 인덱스가 뒤섞임. shift한 결과의 인덱스랑 result의 인덱스가 안맞을 수 있음
# pd.Series()로 감싸면 인덱스를 새로 리셋해서 result테이블이랑 인덱스를 맞춰줌
# pd.Series()는 인덱스가 붙어있는 1차원 배열. DateFrame의 컬럼 하나를 뽑으면 그게 Series임

                 reserve_id hotel_id     reserve_datetime checkin_date  \
customer_id
c_1         0            r1     h_75  2016-03-06 13:09:42   2016-03-26
            1            r2    h_219  2016-07-16 23:39:55   2016-07-20
            2            r3    h_179  2016-09-24 10:03:17   2016-10-19
            3            r4    h_214  2017-03-08 03:20:10   2017-03-29
            4            r5     h_16  2017-09-05 19:50:37   2017-09-22
...                     ...      ...                  ...          ...
c_999       4023      r4024    h_244  2016-10-06 18:01:34   2016-10-07
            4024      r4025    h_160  2017-03-11 11:56:05   2017-03-27
            4025      r4026    h_129  2017-06-27 23:00:02   2017-07-10
            4026      r4027     h_97  2017-09-29 05:24:57   2017-10-09
            4027      r4028     h_27  2018-03-14 05:01:45   2018-04-02

                 checkin_time checkout_date  people_num  total_price  log_no  \
customer_id
c_1         0        10:00:00    2016-03-29           4        97200     1.0
            1        11:30:00    2016-07-21           2        20600     2.0
            2        09:00:00    2016-10-22           2        33600     3.0
            3        11:00:00    2017-03-30           4       194400     4.0
            4        10:30:00    2017-09-23           3        68100     5.0
...                       ...           ...         ...          ...     ...
c_999       4023     11:30:00    2016-10-09           3        59400     2.0
            4024     10:00:00    2017-03-30           1        37200     3.0
            4025     09:30:00    2017-07-11           2        16000     4.0
            4026     10:30:00    2017-10-10           2        41800     5.0
            4027     11:30:00    2018-04-04           2        74800     6.0

                  before_price
customer_id
c_1         0              NaN
            1              NaN
            2          97200.0
            3          20600.0
            4          33600.0
...                        ...
c_999       4023       96000.0
            4024       62400.0
            4025       59400.0
            4026       37200.0
            4027       16000.0

[4030 rows x 10 columns]

In [33]:
import warnings     #파이썬 내장 모듈로 경고메시지를 제어하는거
warnings.filterwarnings('ignore', category=DeprecationWarning)
# 특정 종류의 화면에 출력하지않게하는거고, DeprecationWarning은 더이상 사용되지않는 기능이나 방법에 대한 경고메시지입니다. 이 코드는 DeprecationWarning이 발생하더라도 화면에 출력하지 않도록 설정하는 코드입니다.

## rolling()
창문(window)이 한 칸씩 내려가면서 창문 안의 값을 계산

**그냥 sum vs rolling sum**
- 그냥 sum → 전체 다 더함 (50,000+80,000+120,000+30,000+90,000 = 370,000)
- rolling sum → 3개씩 묶어서 더함

| 예약순 | total_price | 그냥 sum | rolling sum (window=3) |
|-------|-------------|---------|----------------------|
| 1번   | 50,000      | 370,000 | NaN  ← 3개 안참       |
| 2번   | 80,000      | 370,000 | NaN  ← 3개 안참       |
| 3번   | 120,000     | 370,000 | 250,000 ← 1+2+3번    |
| 4번   | 30,000      | 370,000 | 230,000 ← 2+3+4번    |
| 5번   | 90,000      | 370,000 | 240,000 ← 3+4+5번    |

- `window=3` : 창문 크기 (몇 개씩 묶을지)
- `min_periods=3` : 3개 미만이면 NaN
- `center=False` : 현재 행 포함 이전 값들로 계산

In [ ]:
# 과거 n건의 합계를 구하기. 
#고객별로 날짜순 정렬 후, 3번 연속예약 금액을 창문 sliding방식으로 합산하는 코드

# 고객별로 묶어서 날짜순으로 정렬
result=reserve_tb.groupby('customer_id') \
    .apply(lambda x: x.sort_values(by='reserve_datetime', ascending=True)) \
    .reset_index(drop=True) #이 코드는 인덱스를 새로 리셋


result['price_sum']=pd.Series(
    result.loc[:, ['customer_id', 'total_price']]  
    .groupby('customer_id')
    .rolling(center=False, window=3, min_periods=3).sum()
    #cunstomer, total 두 컬럼만 뽑고, 고객별로 묶어서(고객끼리 섞이면 안되니까) 3칸짜리 창문을 내려가면서 합계
    .reset_index(drop=True) #인덱스 새로 리셋
    .loc[:, 'total_price']
)

result

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,price_sum
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0,NaN
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0,NaN
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0,151400.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0,248600.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0,296100.0
...,...,...,...,...,...,...,...,...,...,...,...
4025,r4024,h_244,c_999,2016-10-06 18:01:34,2016-10-07,11:30:00,2016-10-09,3,59400,2.0,NaN
4026,r4025,h_160,c_999,2017-03-11 11:56:05,2017-03-27,10:00:00,2017-03-30,1,37200,3.0,159000.0
4027,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0,112600.0
4028,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0,95000.0
4029,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0,132600.0

In [ ]:
# 이번 예약 전까지의 평균 금액을 구하는 코드. roling으로 이동평균 만들고 shift로 한칸 밀어서 현재 예약 제외
#고객별 날짜순 정렬
result = reserve_tb.groupby('customer_id') \
    .apply(lambda x: x.sort_values(by='reserve_datetime', ascending=True)) \
    .reset_index(drop=True) #인덱스 새로 리셋

result['price_avg'] = pd.Series(
    result
        .groupby('customer_id')
        ['total_price'].rolling(center=False, window=3, min_periods=1).mean()   #3개의 평균,min_periods=1은 NaN없이 처음부터 계산
        .reset_index(drop=True)
)

result['price_avg'] = \
    result.groupby('customer_id')['price_avg'].shift(periods=1) #shift(1)로 1칸 밀기

result

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,price_avg
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0,NaN
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0,97200.000000
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0,58900.000000
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0,50466.666667
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0,82866.666667
...,...,...,...,...,...,...,...,...,...,...,...
4025,r4024,h_244,c_999,2016-10-06 18:01:34,2016-10-07,11:30:00,2016-10-09,3,59400,2.0,62400.000000
4026,r4025,h_160,c_999,2017-03-11 11:56:05,2017-03-27,10:00:00,2017-03-30,1,37200,3.0,60900.000000
4027,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0,53000.000000
4028,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0,37533.333333
4029,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0,31666.666667

In [ ]:
import pandas.tseries.offsets as offsets
import operator

#이 예약 기준으로 과거 90일 안에 결제한 금액의 합계를 구하는 코드

# 1단계 -날짜 변환. 문자열을 날짜 타입으로 변환
reserve_tb['reserve_datetime'] = \
    pd.to_datetime(
        reserve_tb['reserve_datetime'],
        format='%Y-%m-%d %H:%M:%S'
    )

# 2단계 -자기 자신이랑 자기 자신을 merge
sum_table = pd.merge(
    reserve_tb[['reserve_id', 'customer_id', 'reserve_datetime']],
    reserve_tb[['customer_id', 'reserve_datetime', 'total_price']]
        .rename(columns={'reserve_datetime': 'reserve_datetime_before'}),
    on='customer_id' #같은 고객의 모든 예약끼리 연결하도록 customer_id기준으로 merge
)

# 3단계 -90일 조건 필터링
sum_table = sum_table[
    operator.and_(  #operator.and_ 는 두 조건을 동시에 만족하는 것만
        sum_table['reserve_datetime'] > sum_table['reserve_datetime_before'], #현재 예약이 과거 예약보다 나중이어야함(미래에서 과거 방향)
        sum_table['reserve_datetime'] + offsets.Day(-90)  #현재 날짜에서 90일 뺀 날짜(과거 예약 날짜), 즉 과거 90일 안에 있는 예약만
        <= sum_table['reserve_datetime_before']
    )
    # 4단계 -reserve_id별 합계
].groupby('reserve_id')['total_price'].sum().reset_index() #필터링된 과거 90일 예약들을 현재 예약 id별로 합산

sum_table.columns = ['reserve_id', 'total_price_sum']

# 5단계 -원본에 붙이고 NaN은 0으로
pd.merge(
    reserve_tb,
    sum_table,
    on='reserve_id',
    how='left'
).fillna(0)

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,total_price_sum
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0,0.0
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0,0.0
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0,20600.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0,0.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000,4.0,0.0
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800,5.0,0.0
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800,6.0,0.0
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13,4,540000,1.0,0.0
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0,540000.0

In [ ]:
import datetime
from dateutil.relativedelta import relativedelta

#모든 고객 X 모든 월 조합을 만드는 코드

month_mst = pd.DataFrame({
    'year_month':
        [(datetime.date(2017, 1, 1) + relativedelta(months=x)).strftime("%Y%m")  #+ relativedelta(months=x는 X달 더하기
         for x in range(0, 3)]
})

customer_tb['join_key'] = 0 #일반 merge는 공통 값 기준으로 합쳐서 모든 행에 똑같이 0을 넣으면 전부 다 매칭
month_mst['join_key'] = 0

customer_mst = pd.merge(
    customer_tb[['customer_id', 'join_key']],
    month_mst,
    on='join_key'
)

customer_mst

     customer_id  join_key year_month
0            c_1         0     201701
1            c_1         0     201702
2            c_1         0     201703
3            c_2         0     201701
4            c_2         0     201702
...          ...       ...        ...
2995       c_999         0     201702
2996       c_999         0     201703
2997      c_1000         0     201701
2998      c_1000         0     201702
2999      c_1000         0     201703

[3000 rows x 3 columns]