In [1]:
import pandas as pd
import os

def load_hotel_reserve():
  customer_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/customer.csv')
  hotel_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/hotel.csv')
  reserve_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/reserve.csv')
  return customer_tb, hotel_tb, reserve_tb


def load_holiday_mst():
  holiday_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/holiday_mst.csv',
                           index_col=False)
  return holiday_tb


def load_production():
  production_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/production.csv')
  return production_tb


def load_production_missing_num():
  production_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/production_missing_num.csv')
  return production_tb


def load_production_missing_category():
  production_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/production_missing_category.csv')
  return production_tb


def load_monthly_index():
  monthly_index_tb = \
    pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/monthly_index.csv')
  return monthly_index_tb


def load_meros_txt():
  with open('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/txt/meros.txt', 'r') as f:
    meros = f.read()
    f.close()
  return meros

In [2]:
customer_tb, hotel_tb, reserve_tb = load_hotel_reserve()

print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [3]:
reserve_tb[['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime',
            'checkin_date', 'checkin_time', 'checkout_date']]

print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [4]:
reserve_tb.loc[:, ['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime',
                   'checkin_date', 'checkin_time', 'checkout_date']]
print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [5]:
reserve_tb.drop(['people_num', 'total_price'], axis=1, inplace=True)

print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date
0        10:00:00    2016-03-29
1        11:30:00    2016-07-21
2        09:00:00    2016-10-22
3        11:00:00    2017-03-30
4        10:30:00    2017-09-23
...           ...           ...
4025     09:30:00    2017-07-11
4026     10:30:00    2017-10-10
4027     11:30:00    2018-04-04
4028     09:30:00    2016-05-13
4029     09:00:00    2016-07-09

[4030 rows x 7 columns]

In [6]:
reserve_tb[(reserve_tb['checkout_date'] >= '2016-10-13') &
           (reserve_tb['checkout_date'] <= '2016-10-14')]

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [7]:
reserve_tb.loc[(reserve_tb['checkout_date'] >= '2016-10-13') &
               (reserve_tb['checkout_date'] <= '2016-10-14'), :]        #.loc()는 이 조건에 맞는 행+이 컬럼들만 보여달라고하는

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [8]:
reserve_tb.query('"2016-10-13" <= checkout_date <= "2016-10-14"')

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [9]:
reserve_tb.sample(frac=0.5)

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
3752,r3753,h_55,c_935,2016-02-19 08:54:15,2016-03-08,12:30:00,2016-03-10
1358,r1359,h_247,c_333,2016-06-15 18:00:17,2016-06-15,10:30:00,2016-06-18
2794,r2795,h_163,c_704,2017-03-19 13:00:51,2017-04-15,12:30:00,2017-04-18
1501,r1502,h_43,c_369,2017-04-30 01:32:51,2017-05-20,09:30:00,2017-05-22
3036,r3037,h_13,c_766,2016-11-01 21:55:26,2016-11-24,12:00:00,2016-11-25
...,...,...,...,...,...,...,...
1141,r1142,h_260,c_278,2016-10-10 09:22:21,2016-11-04,10:00:00,2016-11-07
3095,r3096,h_173,c_778,2017-04-15 11:23:39,2017-05-06,12:00:00,2017-05-09
792,r793,h_227,c_192,2018-03-10 13:33:53,2018-03-30,10:00:00,2018-04-01
686,r687,h_151,c_168,2016-04-09 23:08:13,2016-04-12,10:30:00,2016-04-15
3426,r3427,h_122,c_855,2016-01-10 17:08:16,2016-01-22,12:00:00,2016-01-25

In [10]:
target= pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)
print(target)

reserve_tb[reserve_tb['customer_id'].isin(target)]

56      c_65
744    c_841
785    c_883
75      c_86
513    c_584
       ...
605    c_689
226    c_259
291    c_334
157    c_184
702    c_797
Length: 444, dtype: object

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
16,r17,h_115,c_3,2016-05-10 12:20:32,2016-05-17,10:00:00,2016-05-19
17,r18,h_132,c_3,2016-10-22 02:18:48,2016-11-12,12:00:00,2016-11-13
18,r19,h_23,c_3,2017-01-11 22:54:09,2017-02-08,10:00:00,2017-02-10
19,r20,h_292,c_3,2017-02-23 07:10:30,2017-03-03,11:00:00,2017-03-04
20,r21,h_153,c_3,2017-04-06 18:12:10,2017-04-16,09:00:00,2017-04-19
...,...,...,...,...,...,...,...
3996,r3997,h_143,c_992,2017-02-23 09:24:00,2017-03-03,09:00:00,2017-03-05
4020,r4021,h_159,c_997,2016-01-08 20:30:10,2016-01-09,12:00:00,2016-01-11
4021,r4022,h_172,c_997,2016-05-13 09:08:55,2016-06-06,09:30:00,2016-06-08
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09

In [11]:
result = reserve_tb \
        .groupby('hotel_id') \
        .agg({'reserve_id' : 'count', 'customer_id': 'nunique' })

# nunique()는 중복제거된 값의 개수만 반환 / unique()는 중복 제거된 값 자체를 반환
# 호텔별로 묶어서, 전체 예약 개수와 서로 다른 고객(중복제거)를 계산하는 코드
# 호텔별로 얼마나 예약이 많이 들어왔고 몇명의 서로 다른 고객이 이용했는지를 보는것

In [12]:
result.reset_index(inplace=True)
result.columns = ['hotel_id', 'rsv_cnt', 'cus_cnt']
print(result)

    hotel_id  rsv_cnt  cus_cnt
0        h_1       10       10
1       h_10        3        3
2      h_100       20       19
3      h_101       17       17
4      h_102       13       13
..       ...      ...      ...
295     h_95       13       13
296     h_96       13       13
297     h_97       16       16
298     h_98       17       16
299     h_99       14       14

[300 rows x 3 columns]

In [13]:
print(reserve_tb.columns)

Index(['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime',
       'checkin_date', 'checkin_time', 'checkout_date'],
      dtype='object')

In [14]:
reserve_tb = pd.read_csv('/workspaces/Preprocessing-excersize/notebooks/Preprocessing-excersize/data/reserve.csv')

In [15]:
# 호텔 + 인원수별로 총 매출 합계 구하는 코드 / 각 호텔에서 인원수별로 총 얼마를 벌었는지 구하는 코드
# \ 이건 줄바꿈(코드 이어쓰기) 용도
result = reserve_tb \
    .groupby(['hotel_id', 'people_num'])['total_price'] \
    .sum().reset_index()

print(result)

     hotel_id  people_num  total_price
0         h_1           1       156600
1         h_1           2       156600
2         h_1           3       391500
3         h_1           4       417600
4        h_10           1        11200
...       ...         ...          ...
1154     h_98           3       793800
1155     h_98           4       453600
1156     h_99           1       179200
1157     h_99           2       448000
1158     h_99           4      1164800

[1159 rows x 3 columns]

In [16]:
result.rename(columns={'total_price': 'price_sum'}, inplace=True)

In [17]:
import numpy as np

result=reserve_tb \
       .groupby('hotel_id') \
       .agg({'total_price': ['max', 'min','mean','median',
                             lambda x : np.percentile(x, q=20)]}) \
       .reset_index()
result.columns=['hotel_id', 'price_max','price_min','price_mean',
                'price_median','price_20per']

print(result)

    hotel_id  price_max  price_min     price_mean  price_median  price_20per
0        h_1     208800      26100  112230.000000      104400.0      73080.0
1       h_10      67200      11200   42933.333333       50400.0      26880.0
2      h_100      57600       4800   27600.000000       28800.0       9600.0
3      h_101     168000      14000   75764.705882       56000.0      30800.0
4      h_102      72000      12000   32769.230769       24000.0      18000.0
..       ...        ...        ...            ...           ...          ...
295     h_95     518400      43200  275815.384615      259200.0     146880.0
296     h_96      66600       7400   33015.384615       29600.0      17760.0
297     h_97     250800      20900   83600.000000       62700.0      20900.0
298     h_98     226800      18900   96723.529412       75600.0      56700.0
299     h_99     268800      44800  128000.000000       89600.0      67200.0

[300 rows x 6 columns]

In [18]:
result = reserve_tb.groupby('hotel_id')\
    .agg({'total_price': ['var','std']}).reset_index()
result.columns=['hotel_id','price_var','price_std']

result

    hotel_id     price_var      price_std
0        h_1  3.186549e+09   56449.526127
1       h_10  8.258133e+08   28736.968061
2      h_100  3.198316e+08   17883.835689
3      h_101  2.402441e+09   49014.703676
4      h_102  3.576923e+08   18912.755159
..       ...           ...            ...
295     h_95  3.313772e+10  182037.696857
296     h_96  3.159231e+08   17774.225072
297     h_97  5.474685e+09   73991.116584
298     h_98  3.432893e+09   58590.896578
299     h_99  5.745428e+09   75798.599541

[300 rows x 3 columns]

In [19]:
result.fillna(0, inplace=True)

In [20]:
#최빈값 계산하는 코드 / round(-3)해서 천단위로 반올림,비슷한 가격대 묶기, mode는 가장 자주 등장한느 값 추출
reserve_tb['total_price'].round(-3).mode()

0    10000
1    20000
2    40000
Name: total_price, dtype: int64

In [21]:
reserve_tb['reserve_datetime']=pd.to_datetime(
    reserve_tb['reserve_datetime'], format='%Y-%m-%d %H:%M:%S'
)

In [22]:
reserve_tb['log_no']=reserve_tb \
    .groupby('customer_id')['reserve_datetime'] \
    .rank(ascending=True, method='first')

In [28]:
rsv_cnt_tb=reserve_tb.groupby('hotel_id').size().reset_index()
rsv_cnt_tb.columns=['hotle_id','rsv_cnt']

In [29]:
rsv_cnt_tb['rsv_cnt_rank']=rsv_cnt_tb['rsv_cnt'].rank(ascending=False, method='min')

In [30]:
rsv_cnt_tb.drop('rsv_cnt', axis=1,inplace=True)